PruebaTecnica/Controllers/SeccionesController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaTecnica.Data.Entities;
using PruebaTecnica.Data.Respositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Controllers
{
    public class SeccionesController:Controller
    {
        private readonly ISeccionRepository _seccionRepository;
        private readonly IGradoRepository _gradoRepository;
        private readonly IAlumnoRepository _alumnoRepository;

        public SeccionesController(ISeccionRepository seccionRepository,
                                    IGradoRepository gradoRepository,
                                    IAlumnoRepository alumnoRepository)
        {
            _seccionRepository = seccionRepository;
            _gradoRepository = gradoRepository;
            _alumnoRepository = alumnoRepository;
        }


        public IActionResult Index()
        {

            var secciones = _seccionRepository.GetAllWithAlumnoGrado();


            return View(secciones);
        }


        public IActionResult Create()
        {
            ViewBag.titulo = "Agregar Seccion";

            var gradosList = _gradoRepository.GetGradosList();
            var alumnosList = _alumnoRepository.GetAlumnosList();

            ViewBag.GradosList = gradosList;
            ViewBag.AlumnosList = alumnosList;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AlumnoGrado alumnoGrado)
        {

            if (ModelState.IsValid)
            {



                //se agrega la seccion
                await _seccionRepository.CreateAsync(alumnoGrado);

                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError(string.Empty, "Existen Campos Requeridos");
            return View(alumnoGrado);
        }




        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.titulo = "Seccion";
            var gradosList = _gradoRepository.GetGradosList();
            var alumnosList = _alumnoRepository.GetAlumnosList();

            ViewBag.GradosList = gradosList;
            ViewBag.AlumnosList = alumnosList;


            if (id == null)
            {
                return NotFound();
            }

            var seccion = await _seccionRepository.GetByIdAsync(id);

            if (seccion == null)
            {
                return NotFound();
            }

            return View(seccion);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(AlumnoGrado alumnoGrado)
        {
            ViewBag.titulo = "Seccion";
            var gradosList = _gradoRepository.GetGradosList();
            var alumnosList = _alumnoRepository.GetAlumnosList();

            ViewBag.GradosList = gradosList;
            ViewBag.AlumnosList = alumnosList;


            if (ModelState.IsValid)
            {
                await _seccionRepository.UpdateAsync(alumnoGrado);

                return RedirectToAction(nameof(Index));

            }

            return View(alumnoGrado);

        }


        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.titulo = "Seccion";
            var gradosList = _gradoRepository.GetGradosList();
            var alumnosList = _alumnoRepository.GetAlumnosList();

            ViewBag.GradosList = gradosList;
            ViewBag.AlumnosList = alumnosList;

            if (id == null)
            {
                return NotFound();
            }

            var seccion = await _seccionRepository.GetByIdAsync(id);

            if (seccion == null)
            {
                return NotFound();
            }

            return View(seccion);

        }

        public async Task<IActionResult> Delete(int id)
        {

            var seccion = await _seccionRepository.GetByIdAsync(id);

            if (seccion == null)
            {
                return NotFound();
            }

            await _seccionRepository.DeleteAsync(seccion);


            return RedirectToAction(nameof(Index));
        }
    }
}

PruebaTecnica/Views/Secciones/Create.cshtml
@model PruebaTecnica.Data.Entities.AlumnoGrado

@{
    ViewData["Title"] = ViewBag.titulo;

}

<h2>Crear Seccion</h2>


<div class="row">

    <div class="col-8">

        <form asp-action="Create">        
            
            <partial name="_seccion"/>

            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Seccion</button>
                <button class="btn btn-danger">Cancelar</button>

            </div>



        </form>

    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Secciones" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Secciones/Details.cshtml
@model PruebaTecnica.Data.Entities.AlumnoGrado

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form>


            <div class="form-group row">
                <label asp-for="Seccion" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="Seccion" class="form-control" readonly />
                    <span asp-validation-for="Seccion"></span>
                </div>
            </div>



            <div class="form-group row">
                <label asp-for="Grado" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <select asp-for="GradoId" asp-items="@ViewBag.GradosList" disabled>
                    </select>
                    <span asp-validation-for="Grado"></span>
                </div>
            </div>


            <div class="form-group row">
                <label asp-for="Alumno" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <select asp-for="AlumnoId" asp-items="@ViewBag.AlumnosList" disabled>
                    </select>
                    <span asp-validation-for="Alumno"></span>
                </div>
            </div>






        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Secciones" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Secciones/Edit.cshtml
@model PruebaTecnica.Data.Entities.AlumnoGrado

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form asp-action="Edit">

            <partial name="_seccion" />         

            
            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Seccion</button>
                <button class="btn btn-danger">Cancelar</button>
            </div>


        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Secciones" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Secciones/Index.cshtml
@model IEnumerable<PruebaTecnica.Data.Entities.AlumnoGrado>

@{
    ViewData["Title"] = ViewBag.titulo;
}

<h1>Listado Secciones</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Nueva Seccion</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Seccion)
            </th>
            <th>
                Alumno
            </th>
            <th>
                Seccion
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Seccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Alumno.FullName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Grado.Nombre)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Editar</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm btn">Detalles</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Eliminar</a>
            </td>
        </tr>
        }
    </tbody>
</table>

PruebaTecnica/Views/Secciones/_seccion.cshtml
@model PruebaTecnica.Data.Entities.AlumnoGrado

<div class="form-group row">
    <label asp-for="Seccion" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="Seccion" class="form-control" />
        <span asp-validation-for="Seccion"></span>
    </div>
</div>



<div class="form-group row">
    <label asp-for="Grado" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <select asp-for="GradoId" asp-items="@ViewBag.GradosList">
        </select>
        <span asp-validation-for="Grado"></span>
    </div>
</div>


<div class="form-group row">
    <label asp-for="Alumno" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <select asp-for="AlumnoId" asp-items="@ViewBag.AlumnosList">
        </select>
        <span asp-validation-for="Alumno"></span>
    </div>
</div>