PruebaTecnica/Controllers/ProfesoresController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaTecnica.Data.Entities;
using PruebaTecnica.Data.Respositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Controllers
{
    public class ProfesoresController : Controller
    {
        private readonly IProfesorRepository _profesorRepository;

        public ProfesoresController(IProfesorRepository profesorRepository)
        {
            _profesorRepository = profesorRepository;
        }




        public IActionResult Index()
        {
            var Profesores = _profesorRepository.GetAll();
            ViewBag.titulo = "Catalogo de Profesores";

            return View(Profesores);
        }

        public IActionResult Create()
        {
            ViewBag.titulo = "Agregar Profesor";

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Profesor profesor)
        {

            if (ModelState.IsValid)
            {
                //se agrega el profesor
                await _profesorRepository.CreateAsync(profesor);

                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError(string.Empty, "Existen Campos Requeridos");
            return View(profesor);

        }

        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.titulo = "Profesor";

            if (id == null)
            {
                return NotFound();
            }

            var profesor = await _profesorRepository.GetByIdAsync(id);

            if (profesor == null)
            {
                return NotFound();
            }

            return View(profesor);

        }


        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.titulo = "Profesor";

            if (id == null)
            {
                return NotFound();
            }

            var profesor = await _profesorRepository.GetByIdAsync(id);

            if (profesor == null)
            {
                return NotFound();
            }

            return View(profesor);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Profesor profesor)
        {
            ViewBag.titulo = "Profesor";

            if (ModelState.IsValid)
            {
                await _profesorRepository.UpdateAsync(profesor);

                return RedirectToAction(nameof(Index));

            }

            return View(profesor);

        }

        public async Task<IActionResult> Delete(int id)
        {

            var profesor = await _profesorRepository.GetByIdAsync(id);

            if (profesor == null)
            {
                return NotFound();
            }

            await _profesorRepository.DeleteAsync(profesor);


            return RedirectToAction(nameof(Index));
        }





    }
}

PruebaTecnica/Views/Profesores/Create.cshtml
@model PruebaTecnica.Data.Entities.Profesor

@{
    ViewData["Title"] = ViewBag.titulo;

}

<h2>Crear Profesor</h2>


<div class="row">

    <div class="col-8">

        <form asp-action="Create">        
            
            <partial name="_profesores"/>

            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Profesor</button>
                <button class="btn btn-danger">Cancelar</button>

            </div>



        </form>

    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Profesores" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Profesores/Details.cshtml
@model PruebaTecnica.Data.Entities.Profesor

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form >          

            <div class="form-group row">
                <label asp-for="Nombre" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="Nombre" class="form-control"  readonly/>
                    <span asp-validation-for="Nombre"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Apellidos" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="Apellidos" class="form-control" readonly />
                    <span asp-validation-for="Apellidos"></span>
                </div>
            </div>


            <div class="form-group row">
                <label asp-for="Genero" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10 disabled" >
                    <select asp-for="Genero"  disabled>
                        <option value="" disabled= "" >Seleccione el Genero</option>
                        <option value="F" di>Femenino</option>
                        <option value="M">Masculino</option>
                    </select>
                    <span asp-validation-for="Genero"></span>
                </div>
            </div>


        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Profesores" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Profesores/Edit.cshtml
@model PruebaTecnica.Data.Entities.Profesor

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form asp-action="Edit">

            <partial name="_profesores" />         

            
            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Profesor</button>
                <button class="btn btn-danger">Cancelar</button>
            </div>


        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Profesores" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Profesores/Index.cshtml
@model IEnumerable<PruebaTecnica.Data.Entities.Profesor>

@{
    ViewData["Title"] = ViewBag.titulo;
}

<h1>Listado de Profesores</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo Profesor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
           
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Editar</a> 
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm btn">Detalles</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

PruebaTecnica/Views/Profesores/_profesores.cshtml
@model PruebaTecnica.Data.Entities.Profesor

<div class="form-group row">
    <label asp-for="Nombre" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre"></span>
    </div>
</div>

<div class="form-group row">
    <label asp-for="Apellidos" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="Apellidos" class="form-control" />
        <span asp-validation-for="Apellidos"></span>
    </div>
</div>


<div class="form-group row">
    <label asp-for="Genero" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <select asp-for="Genero">
            <option value="" disabled="" selected="">Seleccione el Genero</option>
            <option value="F">Femenino</option>
            <option value="M">Masculino</option>
        </select>
        <span asp-validation-for="Genero"></span>
    </div>
</div>