PruebaTecnica/Controllers/AlumnosController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaTecnica.Data.Entities;
using PruebaTecnica.Data.Respositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Controllers
{
    public class AlumnosController : Controller
    {
        private readonly IAlumnoRepository _alumnosRepository;

        public AlumnosController( IAlumnoRepository alumnosRepository)
        {
            _alumnosRepository = alumnosRepository;
        }




        public IActionResult Index()
        {
            var alumnos = _alumnosRepository.GetAll();
            ViewBag.titulo = "Catalogo de Alumnos";

            return View(alumnos);
        }

        public IActionResult Create()
        {
            ViewBag.titulo = "Agregar Alumno";

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create (Alumno alumno)
        {

            if (ModelState.IsValid)
            {
                //se agrega el alumno
                await _alumnosRepository.CreateAsync(alumno);

                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError(string.Empty, "Existen Campos Requeridos");
            return View(alumno);
           
        }

        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.titulo = "Alumno";

            if (id == null)
            {
                return NotFound();
            }

            var alumno = await _alumnosRepository.GetByIdAsync(id);

            if (alumno == null)
            {
                return NotFound();
            }

            return View(alumno);

        }


        public async Task<IActionResult> Edit (int? id)
        {
            ViewBag.titulo = "Alumno";

            if (id== null)
            {
                return NotFound();
            }

            var alumno = await _alumnosRepository.GetByIdAsync(id);

            if (alumno == null)
            {
                return NotFound();
            }

            return View(alumno);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Alumno alumno)
        {
            ViewBag.titulo = "Alumno";

            if (ModelState.IsValid)
            {
                await _alumnosRepository.UpdateAsync(alumno);

                return RedirectToAction(nameof(Index));

            }

            return View(alumno);

        }

        public async Task<IActionResult> Delete(int id)
        {

            var alumno = await _alumnosRepository.GetByIdAsync(id);

            if(alumno == null)
            {
                return NotFound();
            }

            await _alumnosRepository.DeleteAsync(alumno);


            return RedirectToAction(nameof(Index));
        }





    }
}

PruebaTecnica/Views/Alumnos/Create.cshtml
@model PruebaTecnica.Data.Entities.Alumno

@{
    ViewData["Title"] = ViewBag.titulo;

}

<h2>Crear Alumno</h2>


<div class="row">

    <div class="col-8">

        <form asp-action="Create">        
            
            <partial name="_alumnos"/>

            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Alumno</button>
                <button class="btn btn-danger">Cancelar</button>

            </div>



        </form>

    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Alumnos" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Alumnos/Details.cshtml
@model PruebaTecnica.Data.Entities.Alumno

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form >          

            <div class="form-group row">
                <label asp-for="Nombre" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="Nombre" class="form-control"  readonly/>
                    <span asp-validation-for="Nombre"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="Apellidos" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="Apellidos" class="form-control" readonly />
                    <span asp-validation-for="Apellidos"></span>
                </div>
            </div>


            <div class="form-group row">
                <label asp-for="Genero" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10 disabled" >
                    <select asp-for="Genero"  disabled>
                        <option value="" disabled= "" >Seleccione el Genero</option>
                        <option value="F" di>Femenino</option>
                        <option value="M">Masculino</option>
                    </select>
                    <span asp-validation-for="Genero"></span>
                </div>
            </div>

            <div class="form-group row">
                <label asp-for="FechaNacimiento" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="FechaNacimiento" class="form-control" readonly/>
                    <span asp-validation-for="FechaNacimiento"></span>
                </div>
            </div>




        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Alumnos" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Alumnos/Edit.cshtml
@model PruebaTecnica.Data.Entities.Alumno

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form asp-action="Edit">

            <partial name="_alumnos" />         

            
            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Alumno</button>
                <button class="btn btn-danger">Cancelar</button>
            </div>


        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Alumnos" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Alumnos/Index.cshtml
@model IEnumerable<PruebaTecnica.Data.Entities.Alumno>

@{
    ViewData["Title"] = ViewBag.titulo;
}

<h1>Listado de Alumnos</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo Alumno</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Editar</a> 
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm btn">Detalles</a> 
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>

PruebaTecnica/Views/Alumnos/_alumnos.cshtml
@model PruebaTecnica.Data.Entities.Alumno

<div class="form-group row">
    <label asp-for="Nombre" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre"></span>
    </div>
</div>

<div class="form-group row">
    <label asp-for="Apellidos" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="Apellidos" class="form-control" />
        <span asp-validation-for="Apellidos"></span>
    </div>
</div>


<div class="form-group row">
    <label asp-for="Genero" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <select asp-for="Genero">
            <option value="" disabled="" selected="">Seleccione el Genero</option>
            <option value="F">Femenino</option>
            <option value="M">Masculino</option>
        </select>
        <span asp-validation-for="Genero"></span>
    </div>
</div>

<div class="form-group row">
    <label asp-for="FechaNacimiento" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="FechaNacimiento" class="form-control" />
        <span asp-validation-for="FechaNacimiento"></span>
    </div>
</div>