PruebaTecnica/Controllers/GradosController.cs
using Microsoft.AspNetCore.Mvc;
using PruebaTecnica.Data.Entities;
using PruebaTecnica.Data.Respositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PruebaTecnica.Controllers
{
    public class GradosController : Controller
    {
        private readonly IGradoRepository _gradoRepository;
        private readonly IProfesorRepository _profesorRepository;

        public GradosController(IGradoRepository gradoRepository ,
                                IProfesorRepository profesorRepository)
        {
            _gradoRepository = gradoRepository;
            _profesorRepository = profesorRepository;
        }


        public IActionResult Index()
        {

            var grados = _gradoRepository.GetAllWithProfesores();


            return View(grados);
        }


        public IActionResult Create()
        {
            ViewBag.titulo = "Agregar Grado";

            var profesoresList = _profesorRepository.GetProfesoresList();
            ViewBag.profesoresList = profesoresList;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Grado grado)
        {

            if (ModelState.IsValid)
            {



                //se agrega el alumno
                await _gradoRepository.CreateAsync(grado);

                return RedirectToAction(nameof(Index));
            }

            ModelState.AddModelError(string.Empty, "Existen Campos Requeridos");
            return View(grado);
        }




        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.titulo = "Grado";
            var profesoresList = _profesorRepository.GetProfesoresList();
            ViewBag.profesoresList = profesoresList;

            if (id == null)
            {
                return NotFound();
            }

            var grado = await _gradoRepository.GetByIdAsync(id);

            if (grado == null)
            {
                return NotFound();
            }

            return View(grado);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(Grado alumno)
        {
            ViewBag.titulo = "Grado";
            var profesoresList = _profesorRepository.GetProfesoresList();
            ViewBag.profesoresList = profesoresList;

            if (ModelState.IsValid)
            {
                await _gradoRepository.UpdateAsync(alumno);

                return RedirectToAction(nameof(Index));

            }

            return View(alumno);

        }


        public async Task<IActionResult> Details(int? id)
        {
            ViewBag.titulo = "Grado";
            var profesoresList = _profesorRepository.GetProfesoresList();
            ViewBag.profesoresList = profesoresList;

            if (id == null)
            {
                return NotFound();
            }

            var grado = await _gradoRepository.GetByIdAsync(id);

            if (grado == null)
            {
                return NotFound();
            }

            return View(grado);

        }

        public async Task<IActionResult> Delete(int id)
        {

            var grado = await _gradoRepository.GetByIdAsync(id);

            if (grado == null)
            {
                return NotFound();
            }

            await _gradoRepository.DeleteAsync(grado);


            return RedirectToAction(nameof(Index));
        }


    }
}

PruebaTecnica/Views/Grados/Create.cshtml
@model PruebaTecnica.Data.Entities.Grado

@{
    ViewData["Title"] = ViewBag.titulo;

}

<h2>Crear Grado</h2>


<div class="row">

    <div class="col-8">

        <form asp-action="Create">        
            
            <partial name="_grado"/>

            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Grado</button>
                <button class="btn btn-danger">Cancelar</button>

            </div>



        </form>

    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Grados" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Grados/Details.cshtml
@model PruebaTecnica.Data.Entities.Grado

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form>


            <div class="form-group row">
                <label asp-for="Nombre" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <input asp-for="Nombre" class="form-control" readonly/>
                    <span asp-validation-for="Nombre"></span>
                </div>
            </div>



            <div class="form-group row">
                <label asp-for="Profesor" class="form-label col-form-label text-sm-right col-sm-2"></label>
                <div class="input-group col-sm-10">
                    <select asp-for="ProfesorId" asp-items="@ViewBag.ProfesoresList" disabled>
                    </select>
                    <span asp-validation-for="Profesor"></span>
                </div>
            </div>



        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Grados" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Grados/Edit.cshtml
@model PruebaTecnica.Data.Entities.Grado

@{
    ViewData["Title"] = ViewBag.titulo;
}


<h2>Informacion de: </h2>
<div class="row">

    <div class="col-8">

        <form asp-action="Edit">

            <partial name="_grado" />         

            
            <div class="form-group">
                <button class="btn btn-primary " type="submit">Guardar Grado</button>
                <button class="btn btn-danger">Cancelar</button>
            </div>


        </form>




    </div>
    <div class="col-4"></div>


</div>
<div>
    <a class="btn btn-outline-primary" asp-controller="Grados" asp-action="index">Regresar</a>
</div>

PruebaTecnica/Views/Grados/Index.cshtml
@model IEnumerable<PruebaTecnica.Data.Entities.Grado>

@{
    ViewData["Title"] = ViewBag.titulo;
}

<h1>Listado de Grados</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Nuevo Grado</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                Profesor Asignado
            </th>
           
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Profesor.FullName)
                </td>
               
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Editar</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info btn-sm btn">Detalles</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Eliminar</a>
                </td>
            </tr>
        }
    </tbody>
</table>

PruebaTecnica/Views/Grados/_grado.cshtml
@model PruebaTecnica.Data.Entities.Grado

<div class="form-group row">
    <label asp-for="Nombre" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre"></span>
    </div>
</div>



<div class="form-group row">
    <label asp-for="Profesor" class="form-label col-form-label text-sm-right col-sm-2"></label>
    <div class="input-group col-sm-10">
        <select asp-for="ProfesorId" asp-items="@ViewBag.ProfesoresList">
            
        </select>
        <span asp-validation-for="Profesor"></span>
    </div>
</div>